"""1.0 悬浮莉莉丝立绘：把原版分层立绘里的莉莉丝扣出来，做成手机悬浮用的透明素材。

输入（都在仓库里，除了抠图模型）：
  vendor/original/assistant-v1.1.js  里的 ZhuTianLilithLayers（原版 636×948 分层：plate 背景、wings、tail、body、faces 表情补丁）
  assets/lilith/variants/sad.webp      委屈表情（原版分层里没有这一张，从差分立绘的脸部取）
  抠图模型 isnet-anime.onnx（rembg 发布的动漫人物分割模型，不随仓库分发）：
      https://github.com/danielgatis/rembg/releases/download/v0.0.0/isnet-anime.onnx

处理：
  1. plate + wings + tail + body 合成整图，交给 isnet-anime 得到人物蒙版。
  2. body 图层自带的 alpha 和人物蒙版取较小值：去掉 body 图层里残留的背景（左下角星光、头发外的紫雾）。
  3. 只取头到大腿上部 (0,0)-(636,700)，底部 22% 羽化渐隐，所以悬浮时没有一条硬切边。
  4. 两只翅膀分开导出（各自有转轴，悬浮时轻轻扇动）；表情补丁按原版坐标原样导出。

输出：assets/lilith/float/*.webp 和 src/lilith-float-art.js（坐标常量）。
用法：python3 tools/lilith_float_cutout.py /path/to/isnet-anime.onnx
"""
import base64, io, json, re, sys
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'assets/lilith/float'
CROP = (0, 0, 636, 700)          # head → upper thigh, original 636×948 pixel space
FADE = 0.22                      # bottom fraction that fades out
LEVELS = (0.45, 0.90)            # matte → alpha ramp (drops the background haze the model is unsure about)


def layers():
    s = (ROOT / 'vendor/original/assistant-v1.1.js').read_text(encoding='utf8')
    i = s.index('root.ZhuTianLilithLayers=Object.freeze(') + len('root.ZhuTianLilithLayers=Object.freeze(')
    depth = 0
    for j in range(i, len(s)):
        c = s[j]
        if c == '{': depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0: break
    return json.loads(s[i:j + 1])


def img(uri):
    return Image.open(io.BytesIO(base64.b64decode(uri.split(',', 1)[1]))).convert('RGBA')


def matte(full, model):
    import onnxruntime as ort
    x = np.asarray(full.convert('RGB').resize((1024, 1024), Image.LANCZOS)).astype(np.float32) / 255.
    x = (x - np.array([0.485, 0.456, 0.406])).transpose(2, 0, 1)[None].astype(np.float32)
    sess = ort.InferenceSession(model, providers=['CPUExecutionProvider'])
    o = sess.run(None, {sess.get_inputs()[0].name: x})[0][0, 0]
    o = (o - o.min()) / (o.max() - o.min())
    return np.asarray(Image.fromarray((o * 255).astype(np.uint8)).resize(full.size, Image.LANCZOS)).astype(np.float32) / 255.


def fade(a):
    h = a.shape[0]; start = int(h * (1 - FADE))
    t = np.ones(h, np.float32); r = np.linspace(0, 1, h - start)
    t[start:] = 1 - r * r * (3 - 2 * r)            # smoothstep down to 0
    return a * t[:, None]


def save(im, name, q=88):
    im.save(OUT / f'{name}.webp', 'WEBP', quality=q, method=6, exact=False)
    return OUT / f'{name}.webp'


def main(model):
    OUT.mkdir(parents=True, exist_ok=True)
    L = layers(); W, H = L['size']
    plate, wings, tail, body = (img(L['plate']), img(L['wings']), img(L['tail']), img(L['body']))
    full = plate.copy()
    for im in (wings, tail, body): full.alpha_composite(im)
    m = matte(full, model)
    lo, hi = LEVELS
    a = np.minimum(np.asarray(body)[..., 3].astype(np.float32) / 255., np.clip((m - lo) / (hi - lo), 0, 1))
    b = np.asarray(body).copy(); b[..., 3] = (a * 255).astype(np.uint8)
    cx0, cy0, cx1, cy1 = CROP
    def cut(im):
        c = np.asarray(im.crop(CROP)).copy()
        c[..., 3] = (fade(c[..., 3].astype(np.float32) / 255.) * 255).astype(np.uint8)
        return Image.fromarray(c)
    art = {'box': [cx1 - cx0, cy1 - cy0], 'parts': {}, 'faces': {}}
    bc = cut(Image.fromarray(b)); save(bc, 'body')
    art['parts']['body'] = [0, 0, cx1 - cx0, cy1 - cy0]
    # wings: split at the middle, each cropped to its own bounding box
    wc = cut(wings)
    for side, (x0, x1) in (('wingL', (0, (cx1 - cx0) // 2)), ('wingR', ((cx1 - cx0) // 2, cx1 - cx0))):
        part = wc.crop((x0, 0, x1, cy1 - cy0)); bb = part.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
        part = part.crop(bb); save(part, side.lower())
        art['parts'][side] = [x0 + bb[0], bb[1], bb[2] - bb[0], bb[3] - bb[1]]
    # faces: original patches, original coordinates
    for k, f in L['faces'].items():
        save(img(f['src']), f'face-{k}', 92); art['faces'][k] = f['rect']
    # 委屈: from the variant still (424×632 → 636×948), the same face area as 害羞, feathered oval
    rx, ry, rw, rh = L['faces']['shy']['rect']
    sad = Image.open(ROOT / 'assets/lilith/variants/sad.webp').convert('RGBA').resize((W, H), Image.LANCZOS).crop((rx, ry, rx + rw, ry + rh))
    mask = Image.new('L', (rw, rh), 0); ImageDraw.Draw(mask).ellipse((6, 4, rw - 6, rh - 4), fill=255)
    sad.putalpha(mask.filter(ImageFilter.GaussianBlur(7))); save(sad, 'face-sad', 92); art['faces']['sad'] = [rx, ry, rw, rh]
    js = ('// Generated by tools/lilith_float_cutout.py — do not edit by hand.\n'
          '// 1.0 悬浮莉莉丝：原版分层立绘扣出的透明素材（assets/lilith/float）。坐标单位：原版 636×948 像素，裁切框左上为原点。\n'
          f'export const FLOAT_ART = Object.freeze({json.dumps(art, ensure_ascii=False)});\n')
    (ROOT / 'src/lilith-float-art.js').write_text(js, encoding='utf8')
    for p in sorted(OUT.glob('*.webp')): print(f'{p.name:22} {p.stat().st_size:7,d} B')
    print(json.dumps(art))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else '/tmp/isnet-anime.onnx')
